name: Deploy React Webapp to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Hostinger
      run: |
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 ${{secrets.SSH_SERVER_USER}}@${{secrets.SERVER_IP}} << 'EOF'
          if [ ! -d "/energytracker/energytracker_frontend" ]; then
            echo "Cloning repository for the first time..."
            git clone https://github.com/Krontur/energytracker_frontend.git /energytracker/energytracker_frontend
          else
            echo "Updating repository..."
            cd /energytracker/energytracker_frontend
            git pull origin main
          fi
          echo "Making build_and_run.sh executable..."
          chmod +x /energytracker/energytracker_frontend/build_and_run.sh
          echo "Running build_and_run.sh..."
          nohup /energytracker/energytracker_frontend/build_and_run.sh > /dev/null 2>&1 & exit 0
        EOF